### PR TITLE
Add CSS Parser API to biblio.json

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by foolip** [comment]
@tabatkins FYI, this it to get it into specref and https://foolip.github.io/day-to-day/. This spec is still active, right?

**Comment by tabatkins** [comment]
Yes, tho it needs to be cleaned out and redone, since most of its work has been (unexpectedly!) replaced by us just using Typed OM directly.

**Comment by foolip** [comment]
@tabatkins is anyone implementing this, should there be tests in wpt? (Basically, should I exclude it from my radar or not?)

**Comment by tabatkins** [comment]
There's no details yet to actually implement (or test).

**Comment by foolip** [comment]
Exclude it is :)

**Pull request merged**
