### PR TITLE
Add Visual Viewport API to biblio.json

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by foolip** [comment]
@bokand FYI. There's also the question of https://github.com/WICG/admin/issues/42, don't know if just renaming the repo is straightforward. If you want to do that, it's just as well not wait with this PR until afterwards.

**Comment by bokand** [comment]
Yeah, along with w3c/web-platform-tests#7749 I think maybe it'd be better to rename the repo and short-name to `visual-viewport`. WDYT? It sounds like renaming a repo shouldn't be hard, but I'm guessing it might break forks/links etc so let me look into that a bit...

**Comment by foolip** [comment]
visual-viewport SGTM, it matches the name of the interface. When a GitHub repo is renamed, all the old URLs are redirected to the new place, so that's not a problem. You'll still want to update links in various places of course.

@marcoscaceres, can @bokand rename the repo, or does it have to be a WICG admin?

**Comment by marcoscaceres** [comment]
@bokand is admin of that repo, so when he is ready he can rename it through the repo settings.

**Comment by foolip** [comment]
OK, I've updated to point to https://wicg.github.io/visual-viewport/, blocking on @bokand making that URL exist.

**Comment by bokand** [comment]
Done, the new repo is at https://github.com/WICG/visual-viewport and I've updated links to point to this.

**Comment by foolip** [comment]
@bokand, can you also rename spec.html to index.html? Right now the README.md is being served at https://wicg.github.io/visual-viewport/

**Comment by bokand** [comment]
Done

**Pull request merged**
